title: collapsing stars
author: sourcedecay
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  musings on all the things

highlighter: rouge

show_excerpts: true # set to false to remove excerpts on the homepage
highlighter-theme: monokai
date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed

category_dir: category/
tag_dir: tag/

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sourcedecay
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/source.decay/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 
